# Generated by Django 5.2.8 on 2025-12-22 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_product_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profile_status',
            field=models.CharField(default='ACTIVE', max_length=20),
        ),
    ]
